version = 1

exclude_patterns = [
  ".idea/**",
  ".vscode/**",
  ".editorconfig",
  "**.iml"
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"