name: LLMTests
channels:
  - xDazld
  - rapidsai
  - nvidia
  - conda-forge
  - intel
  - nodefaults
dependencies:
  - python=3.11
  - accelerate
  - peft
  - transformers
  - sentencepiece
  - protobuf
  - optimum
  - jupyter
  - cuda
